# Application name
spring.application.name=subtracker-bot
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/subtracker_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.bot.username=subtracker_dj_bot

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

